### ISSUE TITLE
Manual says executable is called "3Bot" actually still called "threebot"

### ISSUE THREAD

**Issue by scottyeager** [threefoldfoundation/info_gridmanual#192] opened 2020-08-16 08:43 UTC
The manual page to create a local 3Bot has been updated to indicate the executable is `3Bot` but the installed executable is still `threebot`.

https://manual2.threefold.io/#/local_3bot

**Comment by xmonader** [comment] 2020-08-16 09:02
definitely caused by a global search and replace

**Comment by xmonader** [comment] 2020-08-18 08:31
closed via ffb3baa0834394e5fd0ce678cecfedbbb51621e4

**Closed by xmonader** 2020-08-18 08:31 UTC
Labels: type_bug
